export const buttonList = [
    {
        id: 1,
        class: 'num',
        text: '7'
    },    {
        id: 2,
        class: 'num',
        text: '8'
    },    {
        id: 3,
        class: 'num',
        text: '9'
    },    {
        id: 4,
        class: 'del',
        text: 'DEL'
    },    {
        id: 5,
        class: 'num',
        text: '4'
    },    {
        id: 6,
        class: 'num',
        text: '5'
    },    {
        id: 7,
        class: 'num',
        text: '6'
    },    {
        id: 8,
        class: 'num',
        text: '+'
    },    {
        id: 9,
        class: 'num',
        text: '1'
    },    {
        id: 10,
        class: 'num',
        text: '2'
    },    {
        id: 11,
        class: 'num',
        text: '3'
    },    {
        id: 12,
        class: 'num',
        text: '-'
    },    {
        id: 13,
        class: 'num',
        text: '.'
    },    {
        id: 14,
        class: 'num',
        text: '0'
    },    {
        id: 15,
        class: 'num',
        text: '/'
    },    {
        id: 16,
        class: 'num',
        text: 'x'
    },    {
        id: 17,
        class: 'reset',
        text: 'RESET'
    },  {
        id: 18,
        class: 'enter',
        text: '='
    },
]